finished backend for Google OAuth
ryan-garay89/berkeley-reentry-student-program pull request #29
Opened 2022-04-04 07:36 UTC by michellekroll

2022-04-04 23:24 UTC, ryan-garay89 requested changes
Once the build is passing, please request review again

2022-04-04 23:24 UTC, ryan-garay89 commented on app/controllers/sessions_controller.rb
> +def googleAuth
This file is malformed (it needs a class definition) which is probably why the build is failing

2022-04-05 17:07 UTC, KLongLo commented on app/models/user.rb
>  end
Also, would you mind changing the code to 2 spaces indent?

2022-04-06 00:38 UTC, ryan-garay89 approved these changes
LGTM!

2022-04-06 02:24 UTC, merged